from enum import Enum

class UserRole(str, Enum):
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    USER = "USER"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"

class MovementEntityType(str, Enum):
    OPERATION = "OPERATION"
    PRODUCT = "PRODUCT"

class MovementType(str, Enum):
    OPERATION_CREATED = "OPERATION_CREATED"
    STATUS_CHANGED = "STATUS_CHANGED"
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_DELETED = "PRODUCT_DELETED"

    LOADED = "LOADED"
    UNLOADED = "UNLOADED"

    IN_TRANSIT = "IN_TRANSIT"
    ARRIVED_AT_HUB = "ARRIVED_AT_HUB"

    DELAY_REPORTED = "DELAY_REPORTED"
    INCIDENT_REPORTED = "INCIDENT_REPORTED"

    CANCELED = "CANCELED"
    UPDATED = "UPDATED"
    COMPLETED = "COMPLETED"

class OperationStatus(str, Enum):
    CREATED = "CREATED"
    AT_ORIGIN = "AT_ORIGIN"
    LOADED = "LOADED"
    IN_TRANSIT = "IN_TRANSIT"
    AT_HUB = "AT_HUB"
    UNLOADED = "UNLOADED"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"
