"""add last_active_at to users

Revision ID: 4539328ac31d
Revises: 8a55b48aa979
Create Date: 2026-02-05 10:32:52.823105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4539328ac31d'
down_revision: Union[str, Sequence[str], None] = '8a55b48aa979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               type_=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               existing_nullable=False)
    op.create_index(op.f('ix_users_last_active_at'), 'users', ['last_active_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_active_at'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               type_=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'last_active_at')
    # ### end Alembic commands ###
