"""incluir campo em operations

Revision ID: 66be3d7d8003
Revises: 573185435c49
Create Date: 2026-02-07 17:05:24.576927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66be3d7d8003'
down_revision: Union[str, Sequence[str], None] = '573185435c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('operation_number', sa.String(length=20), nullable=False))
    op.add_column('operations', sa.Column('partner_id', sa.UUID(), nullable=True))
    op.add_column('operations', sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('operations', sa.Column('type', sa.Enum('DELIVERY', 'PICKUP', 'TRANSFER', 'RETURN', name='operationtype'), nullable=False))
    op.create_index(op.f('ix_operations_operation_number'), 'operations', ['operation_number'], unique=True)
    op.create_index(op.f('ix_operations_partner_id'), 'operations', ['partner_id'], unique=False)
    op.drop_constraint(op.f('operations_updated_by_fkey'), 'operations', type_='foreignkey')
    op.create_foreign_key(None, 'operations', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'operations', 'partners', ['partner_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               type_=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               type_=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               existing_nullable=False)
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.create_foreign_key(op.f('operations_updated_by_fkey'), 'operations', 'users', ['updated_by'], ['id'])
    op.drop_index(op.f('ix_operations_partner_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_operation_number'), table_name='operations')
    op.drop_column('operations', 'type')
    op.drop_column('operations', 'total_value')
    op.drop_column('operations', 'partner_id')
    op.drop_column('operations', 'operation_number')
    # ### end Alembic commands ###
