"""Adiciona token a Company

Revision ID: 7395dace311a
Revises: 
Create Date: 2026-01-19 17:17:01.259773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7395dace311a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('token', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'companies', ['token'])
    op.add_column('operations', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'operations', 'users', ['updated_by'], ['id'])
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               type_=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               type_=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               existing_nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'quantity')
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_column('operations', 'updated_by')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'token')
    # ### end Alembic commands ###
