"""add updater in movements

Revision ID: 87b36061a200
Revises: 4539328ac31d
Create Date: 2026-02-05 12:14:28.820981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87b36061a200'
down_revision: Union[str, Sequence[str], None] = '4539328ac31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               type_=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               type_=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               existing_nullable=False)
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('maintenance_mode', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('allow_registrations', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('session_timeout', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('system_settings_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    # ### end Alembic commands ###
