"""add expected delivery and ip_address

Revision ID: 8a55b48aa979
Revises: df6e4e7668e5
Create Date: 2026-02-05 10:04:06.894464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a55b48aa979'
down_revision: Union[str, Sequence[str], None] = 'df6e4e7668e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('operations', sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               type_=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               type_=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               existing_nullable=False)
    op.drop_column('operations', 'expected_delivery_date')
    op.drop_column('movements', 'ip_address')
    # ### end Alembic commands ###
