"""add fields in company and users

Revision ID: a8a479b91e08
Revises: 3b0eb5073f12
Create Date: 2026-02-02 12:42:36.235941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8a479b91e08'
down_revision: Union[str, Sequence[str], None] = '3b0eb5073f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('stock_alert_limit', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('users', sa.Column('notification_stock_alert', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('notification_weekly_summary', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('theme_preference', sa.String(length=50), nullable=False, server_default='auto'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               type_=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               type_=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'theme_preference')
    op.drop_column('users', 'notification_weekly_summary')
    op.drop_column('users', 'notification_stock_alert')
    op.drop_column('companies', 'stock_alert_limit')
    # ### end Alembic commands ###
