"""add updated_at to users

Revision ID: aa11fd23ce1c
Revises: 7395dace311a
Create Date: 2026-01-28 12:09:42.671346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa11fd23ce1c'
down_revision: Union[str, Sequence[str], None] = '7395dace311a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'companies', ['token'])
    op.add_column('operations', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'operations', 'users', ['updated_by'], ['id'])
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('products', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               type_=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               type_=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'quantity')
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_column('operations', 'updated_by')
    op.drop_constraint(None, 'companies', type_='unique')
    # ### end Alembic commands ###
