"""incluir campo em operations

Revision ID: ad36ecab7fcd
Revises: 66be3d7d8003
Create Date: 2026-02-09 09:08:35.958796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad36ecab7fcd'
down_revision: Union[str, Sequence[str], None] = '66be3d7d8003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('reference_code', sa.String(length=50), nullable=True))
    op.add_column('operations', sa.Column('observation', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_operations_reference_code'), 'operations', ['reference_code'], unique=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               type_=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole', schema='public'),
               type_=postgresql.ENUM('ADMIN', 'MANAGER', 'USER', 'SYSTEM_ADMIN', name='userrole'),
               existing_nullable=False)
    op.drop_index(op.f('ix_operations_reference_code'), table_name='operations')
    op.drop_column('operations', 'observation')
    op.drop_column('operations', 'reference_code')
    # ### end Alembic commands ###
